version: '3.8'

services:
  db:
    image: postgres
    restart: on-failure
    build:
      dockerfile: db.Dockerfile
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db