### Get all employee

GET http://localhost:8080/employee
Content-Type: application/json

### Get employee by companyID

GET http://localhost:8080/company/3/
Content-Type: application/json

### Create employee

POST http://localhost:8080/employee
Content-Type: application/json

{
  "name":"E",
  "surname":"EE",
  "phone":"555",
  "companyID":2,
  "passport": {
    "type":"multi",
    "number":"5555"
  },
  "department": {
    "name":"Отдел №33",
    "phone":"2256"
  }
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### Update employee

PATCH http://localhost:1234/employee/2
Content-Type: application/json

{
  "_":"2023-07-21T11:24:07Z",
  "_": 3
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

### Delete employee

DELETE http://localhost:8080/employee/2/
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}
